### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by balugaq** [SlimefunReloadingProject/RykenSlimeCustomizer#10]
增加类似于动力科技的多方块结构（点击方块召唤生物），比如在多方块机器的配置中加入这种
```yaml
action:   # 操作
  spawn: wither_skeleton  # 召唤凋灵骷髅
  script: a_script_name  # 可增加脚本功能
delete: [1, 4, 7]  # 点击 work 的位置的方块后，设置这些位置为空气
```
