### ISSUE TITLE
关于分类组的建议

### ISSUE THREAD

**Issue by balugaq** [SlimefunReloadingProject/RykenSlimeCustomizer#11]
可以增加类似 Bump 的wiki组（如下）
![8e800f6202aafa5a6500bf03ada470a6](https://github.com/SlimefunReloadingProject/RykenSlimeCustomizer/assets/129668183/bb5866ab-1b61-492e-9038-892c67c3be78)
![e40ec399972620d0c3aa7bc5db206873](https://github.com/SlimefunReloadingProject/RykenSlimeCustomizer/assets/129668183/ccd60cb4-51a1-4cbd-b181-a36ef8373f2f)

```yaml
example_wiki_group:
  type: "wiki"
  link: "example.link.com"
  item:
    name: "&a示例Wiki链接"
    material: KNOWLEDGE_BOOK
    amount: 1
```
