### ISSUE TITLE
[投票]关于添加文件分类的提议  file_classification.yml

### ISSUE THREAD

**Issue by BoXueDuoCai** [SlimefunReloadingProject/RykenSlimeCustomizer#23]
通过文件分类，我们可以更方便、快捷的找到该物品/功能所在文件

`file_classification.yml`
```yaml
# 文件分类

# 第一行为该文件所属类型
# - 为该类型下的文件
# 若第一行未出现的类型 将安装原有读取方式读

# 例如
# armors:
#   - armors.yml
#   - ams.yml
# 则读取armors.yml、ams.yml作为armors的内容进行解析
# 若所有分类无某类型 如 capacitors ， 则直接读取 capacitors.yml
# 

armors:
  - armors.yml
capacitors:
  - capacitors.yml
generators:
  - generators.yml
geo_resources:
  - geo_resources.yml
groups:
  - groups.yml
items:
  - items.yml
machines:
  - machines.yml
mat_generators:
  - mat_generators.yml
mb_machines:
  - mb_machines.yml
menus:
  - menus.yml
mob_drops:
  - mob_drops.yml
recipe_machines:
  - recipe_machines.yml
recipe_types:
  - recipe_types.yml
researches:
  - researches.yml
simple_machines:
  - simple_machines.yml
solar_generators:
  - solar_generators.yml
```
[file_classification.zip](https://github.com/SlimefunReloadingProject/RykenSlimeCustomizer/files/15209833/file_classification.zip)
